
package hellows.client.usingwsimporttool;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldWsImplService", targetNamespace = "http://hellows/", wsdlLocation = "http://localhost:8080/SpringMvcMaven/services/hellosoap?wsdl")
public class HelloWorldWsImplService
    extends Service
{

    private final static URL HELLOWORLDWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDWSIMPLSERVICE_EXCEPTION;
    private final static QName HELLOWORLDWSIMPLSERVICE_QNAME = new QName("http://hellows/", "HelloWorldWsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SpringMvcMaven/services/hellosoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDWSIMPLSERVICE_WSDL_LOCATION = url;
        HELLOWORLDWSIMPLSERVICE_EXCEPTION = e;
    }

    public HelloWorldWsImplService() {
        super(__getWsdlLocation(), HELLOWORLDWSIMPLSERVICE_QNAME);
    }


    public HelloWorldWsImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDWSIMPLSERVICE_QNAME);
    }


    public HelloWorldWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns HelloWorldWs
     */
    @WebEndpoint(name = "HelloWorldWsImplPort")
    public HelloWorldWs getHelloWorldWsImplPort() {
        return super.getPort(new QName("http://hellows/", "HelloWorldWsImplPort"), HelloWorldWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldWs
     */
    @WebEndpoint(name = "HelloWorldWsImplPort")
    public HelloWorldWs getHelloWorldWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hellows/", "HelloWorldWsImplPort"), HelloWorldWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDWSIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDWSIMPLSERVICE_EXCEPTION;
        }
        return HELLOWORLDWSIMPLSERVICE_WSDL_LOCATION;
    }

}
