
package com.rajan.soapauth.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://soapauth.rajan.com/")
public interface HelloWorld {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloToAuthUser", targetNamespace = "http://soapauth.rajan.com/", className = "com.rajan.soapauth.SayHelloToAuthUser")
    @ResponseWrapper(localName = "sayHelloToAuthUserResponse", targetNamespace = "http://soapauth.rajan.com/", className = "com.rajan.soapauth.SayHelloToAuthUserResponse")
    public String sayHelloToAuthUser();

}
